### ISSUE TITLE
Availabiltiy Set is not configured when selecting existing Availability Set

### ISSUE THREAD

**Issue by shinjisgogo** [ShuheiUda/AzurePowerShellCheatsheet#1]
I found that availability set isn't configured when selecting existing Availability Set.
This is because the code only does collect the name of Availability Set but does not collect the resource of availability set selected.

this is my fix code. Please check it out.

# Select Avaiability Set
$AvailabilitySets = @([PSCustomObject]@{"Name" = "Create New"; "Location" = "n/a"; "ResourceGroupName" = "n/a"; "Id" = "n/a"; })
$AvailabilitySets += (Get-AzureRmResourceGroup | Get-AzureRmAvailabilitySet | Select-Object -Property Name,  Location, ResourceGroupName, Id)
$AvailabilitySet = ($AvailabilitySets | Out-GridView -Title "Select Availability Set..." -PassThru).Name
if($AvailabilitySet -eq "Create New"){
    $AvailabilitySet = Read-Host -Prompt "Please input Availability Set name"
    Write-Verbose "Creating new Availability Set `"$AvailabilitySet`""
    $AvailabilitySet = New-AzureRmAvailabilitySet -ResourceGroupName $ResourceGroup.ResourceGroupName -Name $AvailabilitySet -Location $Location
}
**else{
$AvailabilitySet = Get-AzureRmAvailabilitySet -ResourceGroupName $ResourceGroup.ResourceGroupName -Name $AvailabilitySet
}**

thanks

**Comment by ShuheiUda** [comment]
fixed. https://github.com/ShuheiUda/AzurePowerShellCheatsheet/commit/3550d9752c3f37b24573ec6233174c0cab2778f0
